# Generated by Django 5.2 on 2025-08-26 09:59

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('messages_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('pin_code', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('is_agent', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.login')),
                ('messages', models.ManyToManyField(blank=True, related_name='agents', to='agents.inbox')),
            ],
        ),
    ]
