# Generated by Django 5.1.7 on 2025-03-28 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial'), ('offplan', 'OffPlan')], max_length=20)),
                ('caption', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('messages_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCommercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('land_mark', models.TextField(max_length=100)),
                ('sequrity_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('Time_perioud', models.CharField(blank=True, max_length=50, verbose_name='Time Period')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False, verbose_name='Is Disabled?')),
                ('amenities', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCommercialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agent_com/images/')),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentcommercial')),
            ],
        ),
        migrations.CreateModel(
            name='AgentHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('house_area', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('furnished', models.BooleanField(default=False, verbose_name='Is Furnished?')),
                ('land_mark', models.TextField(max_length=100)),
                ('Bedroom', models.CharField(max_length=10)),
                ('Bathroom', models.CharField(max_length=10)),
                ('Kitchen', models.BooleanField(default=False)),
                ('allowed_persons', models.IntegerField(blank=True, null=True, verbose_name='Allowed Persons')),
                ('sequrity_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('Time_perioud', models.CharField(blank=True, max_length=50, verbose_name='Time Period')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('mixed', 'mixed')], default='male', max_length=50)),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False, verbose_name='Is Disabled?')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='AgentHouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agent_houses/images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agenthouse')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('space_area', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('furnished', models.BooleanField(default=False)),
                ('land_mark', models.TextField(max_length=100)),
                ('sequrity_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('Time_perioud', models.CharField(blank=True, max_length=50, verbose_name='Time Period')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False, verbose_name='Is Disabled?')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agent_land/images/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentland')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOffPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('rooms', models.CharField(max_length=10)),
                ('land_mark', models.TextField(max_length=100)),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False, verbose_name='Is Disabled?')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOffPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agent_off/images/')),
                ('offplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentoffplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('pin_code', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('is_agent', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.login')),
                ('messages', models.ManyToManyField(blank=True, related_name='agents', to='agents.inbox')),
            ],
        ),
    ]
