# Generated by Django 5.2 on 2025-09-01 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='developer.premium'),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
