# Generated by Django 5.2 on 2025-06-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcommercial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory'),
        ),
        migrations.AddField(
            model_name='agentcommercialimage',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentcommercial'),
        ),
        migrations.AddField(
            model_name='agenthouse',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory'),
        ),
        migrations.AddField(
            model_name='agenthouseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agenthouse'),
        ),
        migrations.AddField(
            model_name='agentland',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory'),
        ),
        migrations.AddField(
            model_name='agentlandimage',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentland'),
        ),
        migrations.AddField(
            model_name='agentoffplan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory'),
        ),
        migrations.AddField(
            model_name='agentoffplanimage',
            name='offplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentoffplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.inbox'),
        ),
    ]
