# Generated by Django 5.1.7 on 2025-03-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcommercial',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agenthouse',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentland',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentoffplan',
            name='agent',
        ),
    ]
