# Generated by Django 5.1.7 on 2025-03-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_remove_agentcommercial_agent_remove_agenthouse_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenthouseimage',
            old_name='agenthouse',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='agentlandimage',
            old_name='agentland',
            new_name='land',
        ),
    ]
