# Generated by Django 5.2 on 2025-09-01 12:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_userprofile_login_delete_login'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('land_area', models.CharField(max_length=100)),
                ('sq_ft', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('amenities', models.CharField(blank=True, max_length=100, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('perprice', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('land_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.category')),
                ('purposes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.purpose')),
            ],
        ),
    ]
