# Generated by Django 5.2 on 2025-09-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentproperty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentproperty',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='agentproperty',
            old_name='purposes',
            new_name='purpose',
        ),
    ]
