# Generated by Django 5.2 on 2025-09-01 12:13

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_rename_categories_agentproperty_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentproperty')),
            ],
        ),
    ]
