# Generated by Django 5.1.7 on 2025-03-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcommercialimage',
            old_name='agentcom',
            new_name='com',
        ),
    ]
