# Generated by Django 5.2 on 2025-09-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentproperty_agent'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developer.premium'),
        ),
    ]
