# Generated by Django 5.2 on 2025-09-17 11:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
