# Generated by Django 5.1.6 on 2025-02-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('house_area', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('furnished', models.BooleanField(default=False)),
                ('land_mark', models.TextField(max_length=100)),
                ('Bedroom', models.CharField(max_length=10)),
                ('Bathroom', models.CharField(max_length=10)),
                ('Kitchen', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='House-images/')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
    ]
