# Generated by Django 5.2 on 2025-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredproperty',
            name='location',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.URLField(help_text='Paste Google Maps embed/share link here', max_length=1000),
        ),
    ]
