# Generated by Django 5.2 on 2025-08-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
