# Generated by Django 5.1.7 on 2025-03-28 11:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_houseimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='houseimage',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
