# Generated by Django 5.1.6 on 2025-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_house_contact_house_disabled_house_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
