# Generated by Django 5.2 on 2025-09-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_expiredproperty_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.URLField(help_text='Paste Google Maps share OR embed link', max_length=1000),
        ),
    ]
