# Generated by Django 5.2 on 2025-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
