# Generated by Django 5.2 on 2025-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_premiumimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredpremium',
            name='image',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='image',
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='premium',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='premium',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='premium',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='PremiumImage',
        ),
    ]
