# Generated by Django 5.2 on 2025-08-28 05:55

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_remove_expiredpremium_image_remove_premium_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredpremium',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='buysel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premium',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='buysel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, default=365, null=True),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='premium',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='premium',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, default=365, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='premium',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PremiumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('expired_premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.expiredpremium')),
                ('premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.premium')),
            ],
        ),
    ]
