# Generated by Django 5.1.7 on 2025-04-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_commercial_created_at_offplan_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='furnished',
        ),
    ]
