# Generated by Django 5.1.6 on 2025-02-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_house_price_land_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='land',
            name='amenitis',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='space_area',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('land_mark', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='House-images/')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
    ]
