# Generated by Django 5.2 on 2025-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_expiredproperty_screenshot_property_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='perprice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=12),
        ),
    ]
