# Generated by Django 5.1.6 on 2025-02-12 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_rename_name_house_category_rename_name_land_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='image',
            field=models.ImageField(upload_to='commercial-images/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ImageField(upload_to='Land-images/'),
        ),
        migrations.CreateModel(
            name='OffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('rooms', models.CharField(max_length=10)),
                ('land_mark', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='off_plan-images/')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
    ]
