# Generated by Django 5.1.6 on 2025-02-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_alter_commercial_image_alter_land_image_offplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='category',
        ),
        migrations.RemoveField(
            model_name='land',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offplan',
            name='category',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
        migrations.DeleteModel(
            name='OffPlan',
        ),
    ]
