# Generated by Django 5.1.6 on 2025-02-12 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0008_remove_house_category_remove_land_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('space_area', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('furnished', models.BooleanField(default=False)),
                ('land_mark', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='Land-images/')),
                ('sequrity_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('Time_perioud', models.CharField(blank=True, max_length=50, verbose_name='Time Period')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('house_area', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('furnished', models.BooleanField(default=False, verbose_name='Is Furnished?')),
                ('land_mark', models.TextField(max_length=100)),
                ('Bedroom', models.CharField(max_length=10)),
                ('Bathroom', models.CharField(max_length=10)),
                ('Kitchen', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='House-images/')),
                ('allowed_persons', models.IntegerField(blank=True, verbose_name='Allowed Persons')),
                ('sequrity_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('Time_perioud', models.CharField(blank=True, max_length=50, verbose_name='Time Period')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='Genre')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False, verbose_name='Is Disabled?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('land_mark', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='commercial-images/')),
                ('sequrity_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('Time_perioud', models.CharField(blank=True, max_length=50, verbose_name='Time Period')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='OffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=100)),
                ('total_land', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('rooms', models.CharField(max_length=10)),
                ('land_mark', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='off_plan-images/')),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.maincategory')),
            ],
        ),
    ]
