# Generated by Django 5.1.6 on 2025-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='allowed_persons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Allowed Persons'),
        ),
    ]
