# Generated by Django 5.1.6 on 2025-02-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_alter_house_allowed_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='name',
            new_name='catgory',
        ),
    ]
