# Generated by Django 5.1.6 on 2025-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0012_rename_name_maincategory_catgory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='catgory',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Resell', 'Resell'), ('Lease', 'Lease')], max_length=50),
        ),
    ]
