# Generated by Django 5.1.6 on 2025-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0013_alter_maincategory_catgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='genre',
        ),
        migrations.AddField(
            model_name='house',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('mixed', 'mixed')], default='male', max_length=50),
        ),
    ]
