# Generated by Django 5.1.6 on 2025-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0014_remove_house_genre_house_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='amenities',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
