# Generated by Django 5.1.6 on 2025-02-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0015_commercial_amenities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
