# Generated by Django 5.1.6 on 2025-02-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0017_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image1',
            field=models.ImageField(default=1, upload_to='houses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(default=1, upload_to='houses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(default=1, upload_to='houses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(default=1, upload_to='houses'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
