# Generated by Django 5.1.6 on 2025-02-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0018_house_image1_house_image2_house_image3_house_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='image1',
            field=models.ImageField(default=1, upload_to='comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='image2',
            field=models.ImageField(default=1, upload_to='comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='image3',
            field=models.ImageField(default=1, upload_to='comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercial',
            name='image4',
            field=models.ImageField(default=1, upload_to='comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image1',
            field=models.ImageField(default=1, upload_to='land'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image2',
            field=models.ImageField(default=1, upload_to='land'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image3',
            field=models.ImageField(default=1, upload_to='land'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image4',
            field=models.ImageField(default=1, upload_to='land'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offplan',
            name='image1',
            field=models.ImageField(default=1, upload_to='offplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offplan',
            name='image2',
            field=models.ImageField(default=1, upload_to='offplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offplan',
            name='image3',
            field=models.ImageField(default=1, upload_to='offplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offplan',
            name='image4',
            field=models.ImageField(default=1, upload_to='offplan'),
            preserve_default=False,
        ),
    ]
