# Generated by Django 5.1.6 on 2025-02-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0019_commercial_image1_commercial_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
        migrations.RemoveField(
            model_name='offplan',
            name='image',
        ),
    ]
