# Generated by Django 5.1.6 on 2025-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0020_remove_commercial_image_remove_house_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('Dealings', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agent-image')),
            ],
        ),
    ]
