# Generated by Django 5.1.6 on 2025-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0021_agentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('about_the_property', models.TextField()),
                ('image', models.ImageField(upload_to='property-image')),
            ],
        ),
    ]
