# Generated by Django 5.1.3 on 2025-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0022_propertylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_head', models.CharField(max_length=100)),
                ('modal_head', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('card_paragraph', models.TextField()),
                ('modal_paragraph', models.TextField()),
                ('keyword', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blogs')),
            ],
        ),
    ]
