# Generated by Django 5.1.3 on 2025-03-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0023_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='keyword',
        ),
    ]
