# Generated by Django 5.1.7 on 2025-03-22 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0027_alter_commercial_id_alter_house_id_alter_land_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='house',
            name='image4',
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.house')),
            ],
        ),
    ]
