# Generated by Django 5.1.7 on 2025-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0028_remove_house_image1_remove_house_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
