# Generated by Django 5.1.7 on 2025-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0030_houseimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default=1, upload_to='houses'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
