# Generated by Django 5.1.7 on 2025-03-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0032_houseimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offplan',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='land',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='offplan',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='offplan',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='offplan',
            name='image4',
        ),
        migrations.AddField(
            model_name='commercial',
            name='image',
            field=models.ImageField(default=1, upload_to='land'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ImageField(default=1, upload_to='lands'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommercialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commercial_images/')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.commercial')),
            ],
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_images/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.land')),
            ],
        ),
        migrations.CreateModel(
            name='OffplanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offplan_images/')),
                ('offplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.offplan')),
            ],
        ),
    ]
