from django.urls import path
from . import views
urlpatterns = [
    path('',views.admin_page,name='admin_panel'),
    path('base2', views.base, name="base2"),
    path('superuser-login/', views.superuser_login_view,name="superuser_login_view" ),
    # path('agenthouse/<uuid:pk>//edit/', views.agent_house_update, name='agenthouse-update'),
    path('house_create', views.houses_create, name='house_create'),
    path('house/<uuid:pk>/update/', views.houseupdate, name='house_update'),
    path('house/<uuid:pk>/delete/', views.housedelete, name='housedelete'),
    path('land/create/', views.lands_create, name='lands_create'),
    path('land/<uuid:pk>/update/', views.land_update, name='land_update'),
    path('land/<uuid:pk>/delete/', views.land_delete, name='land_delete'),
    path('commercial/create/', views.commercial_create, name='commercial_create'),
    path('commercial/<uuid:pk>/update/', views.commercial_update, name='commercial_update'),
    path('commercial/<uuid:pk>/delete/', views.commercial_delete, name='commercial_delete'),
    path('offplan/create/', views.offplan_create, name='offplan_create'),
    path('offplan/<uuid:pk>/update/', views.offplan_update, name='offplan_update'),
    path('offplan/<uuid:pk>/delete/', views.offplan_delete, name='offplan_delete'),
    path('profiles/create/', views.userprofile_create, name='userprofile_create'),
    path('create/', views.create_blog, name='create_blog'),
    path('update/<int:blog_id>/', views.update_blog, name='update_blog'),
    path('delete/<int:pk>/', views.delete_blog, name='delete_blog'),
    path('delete/inbox/<int:pk>/', views.inbox_delete, name='delete_inbox'),
    path('agenthouse/delete/<uuid:pk>/', views.agent_house_delete, name='agenthouse_delete'),
    path('admin_panel/agenthouse/detail/<uuid:pk>/', views.agenthouse_detail, name='agenthouse_detail'),
    path('agentland/delete/<uuid:pk>/', views.agent_land_delete, name='agentland_delete'),
    path('admin_panel/agentland/detail/<uuid:pk>/', views.agentland_detail, name='agentland_detail'),
    path('agentcom/delete/<uuid:pk>/', views.agent_com_delete, name='agentcom_delete'),
    path('admin_panel/agentcom/detail/<uuid:pk>/', views.agentcom_detail, name='agentcom_detail'),
    path('agentoff/delete/<uuid:pk>/', views.agent_offplan_delete, name='agentoffplan_delete'),
    path('admin_panel/agentoffplan/detail/<uuid:pk>/', views.agentoffplan_detail, name='agentoffplan_detail'),
    path('agent_register/', views.agent_register, name='agent_register'),
    path('logins/<int:id>/delete/', views.login_delete, name='login_delete'),
    path('logout/', views.superuser_logout_view, name='superuser_logout'),

]